Fix race condition and Delta Operation incomplete generation
minio/rsync-go pull request #4
Opened 2024-08-14 20:43 UTC by mdouchement

Fix #3 

```
$ go test -run=NONE -fuzz=FuzzSync -race
fuzz: elapsed: 0s, gathering baseline coverage: 0/76 completed
fuzz: elapsed: 0s, gathering baseline coverage: 76/76 completed, now fuzzing with 16 workers
fuzz: elapsed: 3s, execs: 22875 (7624/sec), new interesting: 7 (total: 83)
fuzz: elapsed: 6s, execs: 51585 (9567/sec), new interesting: 9 (total: 85)
fuzz: elapsed: 9s, execs: 78026 (8802/sec), new interesting: 9 (total: 85)
...
fuzz: elapsed: 10m6s, execs: 6970026 (11394/sec), new interesting: 22 (total: 110)
fuzz: elapsed: 10m9s, execs: 7004121 (11363/sec), new interesting: 22 (total: 110)
fuzz: elapsed: 10m12s, execs: 7021020 (6222/sec), new interesting: 22 (total: 110)
PASS
ok      github.com/minio/rsync-go       613.028s
```

2024-08-14 20:58 UTC, harshavardhana requested changes

2024-08-14 20:58 UTC, harshavardhana commented on example_test.go
> +	_, _ = oldReader.Seek(0, io.SeekStart)
```suggestion
	_, _ = oldReader.Seek(0, io.SeekStart)
```

Can you make sure to only send just this change? all other changes are not needed.

2024-08-14 20:58 UTC, harshavardhana commented on fuzzing_test.go
> +package rsync_test
Add copyright header from the rsync.go file

2024-08-14 20:58 UTC, harshavardhana commented on go.mod
> +	github.com/stretchr/testify v1.9.0
do not want to use testify please use simple things like go's testing package.

2024-08-15 08:32 UTC, mdouchement commented on go.mod
>  go 1.17
How about:
```suggestion
go 1.22
```

In the fuzzing test, `math/rand/v2` is imported which is part of go1.22 release.
`go test` / `go vet` are broken when executed on go1.17 (in the current state of this PR), it should be still importable.
Updating a Golang project version is quite easy.

On the other hand, we can downgrade to `math/rand`.

2024-08-15 08:49 UTC, mdouchement commented on go.mod
>  go 1.17
https://github.com/minio/rsync-go/blob/8dc6f97e7eef301a78c9e5b827255a7c44f76eac/.github/workflows/vulncheck.yml#L17
needs to be updated too

2024-08-17 22:07 UTC, harshavardhana approved these changes

2024-08-17 22:08 UTC, merged